default:
  outputs:
    dev:
      type: snowflake
      account: [your account]
      user: [your user]
      password: [your password]
      role: TRANSFORMER
      database: PROD
      warehouse: TRANSFORMING
      schema: ANALYTICS
      threads: 8
      client_session_keep_alive: False

  target: dev