config:
  send_anonymous_usage_stats: False

default:
  outputs:
    dev: # User-Password config
      type: snowflake
      account: us99336.ap-southeast-2
      user: Jarvis
      password: JarvisLoveTech2022
      role: ACCOUNTADMIN
      database: PROD
      warehouse: TRANSFORMING
      schema: ANALYTICS
      threads: 8
      client_session_keep_alive: False

  target: dev